name: Run Tests

on:
  push:
    branches: [main,beta]
  pull_request:
    branches: [main,beta]

jobs:
  test-main:
    name: Test Main SDK (Python 3.9)
    runs-on: ubuntu-latest
    env:
      MAXIM_API_KEY: ${{ secrets.MAXIM_API_KEY }}
      MAXIM_LOG_REPO_ID: ${{ secrets.MAXIM_LOG_REPO_ID }}
      MAXIM_BASE_URL: ${{ secrets.MAXIM_BASE_URL }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
      GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
      FIREWORKS_API_KEY: ${{ secrets.FIREWORKS_API_KEY }}
      MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
      TOGETHER_API_KEY: ${{ secrets.TOGETHER_API_KEY }}
      TAVILY_API_KEY: ${{ secrets.TAVILY_API_KEY }}

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"

      - name: Set up Python 3.9
        run: uv python install 3.9

      - name: Backup pyproject.toml
        run: |
          cp pyproject.toml pyproject.toml.bak

      - name: Remove additional dependencies
        run: |
          sed -i.bak '/additional_dev = \[/,/\]/d' pyproject.toml

      - name: Install dependencies (dev only)
        run: |
          uv sync --python 3.9

      - name: Run main tests (excluding CrewAI)
        run: |
          uv run pytest tests/ -v --ignore=tests/integrations/crewai/ --ignore=tests/test_livekit.py --ignore=tests/test_livekit_realtime.py

      - name: Restore pyproject.toml
        run: |
          mv pyproject.toml.bak pyproject.toml

  additional-tests:
    name: Test Additional Integrations (Python 3.10)
    runs-on: ubuntu-latest
    env:
      MAXIM_API_KEY: ${{ secrets.MAXIM_API_KEY }}
      MAXIM_BASE_URL: ${{ secrets.MAXIM_BASE_URL }}
      MAXIM_LOG_REPO_ID: ${{ secrets.MAXIM_LOG_REPO_ID }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"

      - name: Set up Python 3.10
        run: uv python install 3.10

      - name: Install dependencies (CrewAI only)
        run: |
          uv sync --python 3.10

      - name: Run additional integration tests
        run: |
          uv run pytest tests/integrations/crewai/