name: Run Tests

on:
  push:
    branches: [main,beta]
  pull_request:
    branches: [main,beta]

jobs:
  test-main:
    name: Test Main SDK (Python 3.9)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"

      - name: Set up Python 3.9
        run: uv python install 3.9

      - name: Backup pyproject.toml
        run: |
          cp pyproject.toml pyproject.toml.bak

      - name: Remove additional dependencies
        run: |
          sed -i.bak '/additional_dev = \[/,/\]/d' pyproject.toml

      - name: Install dependencies (dev only)
        run: |
          uv sync --python 3.9

      - name: Run main tests (excluding CrewAI)
        run: |
          uv run pytest maxim/tests/ -v --ignore=maxim/tests/test_crewai.py --ignore=maxim/tests/test_livekit.py --ignore=maxim/tests/test_livekit_realtime.py --ignore=maxim/tests/test_agno.py

      - name: Restore pyproject.toml
        run: |
          mv pyproject.toml.bak pyproject.toml

  additional-tests:
    name: Test Additional Integrations (Python 3.10)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"

      - name: Set up Python 3.10
        run: uv python install 3.10

      - name: Install dependencies (CrewAI only)
        run: |
          uv sync --python 3.10

      - name: Run additional integration tests
        run: |
          uv run pytest maxim/tests/test_crewai.py